language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - PLATFORM_VERSION=192
#  - PLATFORM_VERSION=193

# https://guides.gradle.org/executing-gradle-builds-on-travisci/
script:
  - ./gradlew buildPlugin -PplatformVersion=$PLATFORM_VERSION

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: "O9ncLMu+4NI4R/L+6WcsNNUIYHMSpToWy3QxHwZp0KmRBMNrkiV+w1VPdYEPgzSO4QqwHu9P4OKI7PEIF3Os/+fqzYx549RuCnb0R61m6vUyrkVAjt94jWjq8NZzS1nikrU/GVmsq6o8Z1NfBo9Q7Y64U1b/ON5SeCPqtT3dV31TUbjpLhvPX1OM9LNgPl/0FHIagpEJULfCgLDMbPZ/FsU1j2Tev3LoKB5PGy4+NHe0tQhCEjdnr6Nlh0V6pfqwBtXZhjd/lNvI1pVv5ySfoCEP81iwnYTENr078W6vaIaAkvXrUhysxgHMwJyBqC0OaJ9x3iPeOiutB1R0kFnSVOagTiDRZhqXia1T/O5/bYkvzGaakjgAnVTHw91Whx8WxnhJxLMiUctwP164Az3c27ZlzQ6XV9OQLd8V5APZcpnk+h96E84qZJUlicAMeVfLISweyZFQye1MkjkEm4KxvFdYq2vOljs6tk2/9lOb7o4Bjg9n3s4Py/S/QYjOOEIvNUg4AikYN6B8k+ZJoci9ewmNH1+DD0cNh05jH+X7lliTh9xe91OA11GBsa7DPKe76kE0Z2du4yzzoOjxoKLabZKaSObMQ6GxciilqbjfkffJWPtFSaDg/gGlP+BWxKIkx/MrHpOsKQMhaDl5aIy0OiOHlesPCTItYfQ56/hVrW4="
  draft: true
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true